---
all:
  children:
    infra:
      hosts:
        u01:
          ansible_host: 192.168.65.17
    kube:
      hosts:
        kube01:
          ansible_host: 192.168.65.27
        kube02:
          ansible_host: 192.168.65.28
        kube03:
          ansible_host: 192.168.65.29
    test:
      hosts:
        u02:
          ansible_host: 192.168.65.18
        u03:
          ansible_host: 192.168.65.30
    ex294:
      hosts:
        ex294_01:
          ansible_host: 192.168.65.31
        ex294_02:
          ansible_host: 192.168.65.32
        ex294_03:
          ansible_host: 192.168.65.33
    office:
      hosts:
        eins:
          ansible_host: 192.168.64.3
        zwei:
          ansible_host: 192.168.64.4
        drei:
          ansible_host: 192.168.64.5
        vier:
          ansible_host: 192.168.64.6

